[package]
authors = ["Kisio Digital <team.coretools@kisio.org>", "Guillaume Pinot <texitoi@texitoi.eu>"]
name = "transit_model"
version = "0.8.0"
license = "AGPL-3.0"
description = "Transit data management"
repository = "https://github.com/CanalTP/transit_model"
keywords = ["ntfs", "gtfs", "netex", "navitia", "transit"]
edition = "2018"

[badges]
travis-ci = { repository = "CanalTP/transit_model" }

[workspace]
members = [
    ".",
    "./libs/collection",
    "./libs/relations",
    "./libs/transit_model_procmacro",
    "./libs/model-builder"
]

[dependencies]
chrono = "0.4"
csv = "1.0"
derivative = "1"
env_logger = "0.6"
failure = "0.1"
geo = "0.12"
geo-types = "0.4"
iso4217 = "0.3"
lazy_static = "1.2"
log = "0.4"
minidom = "0.9"
num-traits = "0.2"
pretty_assertions = "0.6"
proj = { version = "0.10", optional = true }
rust_decimal = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
tempfile = "3"
time-parse = "0.1"
transit_model_procmacro = { version = "0.1", path = "./libs/transit_model_procmacro" }
walkdir = "2.1"
wkt = "0.5"
zip = "0.5"
transit_model_collection = { path = "./libs/collection" }
transit_model_relations = { path = "./libs/relations" }

[[test]]
name = "kv12ntfs"
path = "tests/read_kv1.rs"
required-features = ["proj"]

[[test]]
name = "transxchange2ntfs"
path = "tests/read_transxchange.rs"
required-features = ["proj"]

[dev-dependencies]
approx = "0.3"
rust_decimal_macros = "1.0"
